Strings
avaturrr/Ksyusha pull request #2
Opened 2023-03-01 17:04 UTC by avaturrr

2023-03-01 18:05 UTC, maks1makrov requested changes

2023-03-01 18:05 UTC, maks1makrov commented on strings/strings_01.py
> +length_str = "Привет, меня зовут " + firstname + " " + lastname + ", мне " + age + " лет"
надо было бы определить эту переменную до принта в 7 строке, и уже эту переменную принтить

2023-03-01 18:05 UTC, maks1makrov commented on strings/strings_05.py
> +print(my_line[4:len(my_line)-1:3])
len(my_line)-1 - это предпоследний а в задании сказано про предпредпоследний - т.е len(my_line)-2 или просто -2

2023-03-04 08:38 UTC, avaturrr commented on strings/strings_05.py
> +print(my_line[4:len(my_line)-1:3])
а, ну да точно. я невнимательно прочитала

2023-03-04 08:38 UTC, avaturrr commented on strings/strings_01.py
> +length_str = "Привет, меня зовут " + firstname + " " + lastname + ", мне " + age + " лет"
а почему? вроде ж работает. для красоты?

2023-03-08 13:57 UTC, maks1makrov commented on strings/strings_01.py
> +length_str = "Привет, меня зовут " + firstname + " " + lastname + ", мне " + age + " лет"
и для удобства и по принципу DRY - прочитай что это такое

2023-03-08 13:58 UTC, maks1makrov approved these changes

2023-03-09 18:16 UTC, merged